### ISSUE TITLE
Clear out code cruft

### ISSUE THREAD

**Issue by magsol** [quinngroup/fergus-ssl#3]
3-4 years of inactivity on the codebase has (likely) led to code rot. Thorough testing (e.g., issue #1) should highlight any fixes that are needed. Make sure the code can run on Python 3.

**Comment by magsol** [comment]
"Code cruft" includes things like:
- `fp_clean.py`: version control (git) takes care of restoring anything that we want to restore, so we don't need to keep copies around
- Global variables on [line 11](https://github.com/quinngroup/fergus-ssl/blob/master/src/fergus_propagation.py#L11) need to be removed.
- Code that is commented out ([line 126](https://github.com/quinngroup/fergus-ssl/blob/master/src/fergus_propagation.py#L126) through [line 174](https://github.com/quinngroup/fergus-ssl/blob/master/src/fergus_propagation.py#L174)), for the same reason as before: version control will restore things if we think we need them again.
- Unused methods, such as `_img_rbf_kernel` ([line 195](https://github.com/quinngroup/fergus-ssl/blob/master/src/fergus_propagation.py#L195)).

**Comment by mgadgil09** [comment]
Removed fp_clean.py. Removed global variables. Removed all the unnecessary code and unused methods.
