### ISSUE TITLE
usage of label_distributions_ unclear. Giving AttributeError

### ISSUE THREAD

**Issue by mgadgil09** [quinngroup/fergus-ssl#5]
attribute **label_distributions_** is being used in the predict_proba() method but it is not initialized anywhere. Since its significance is unclear, unable to debug the issue.

 _File "Computational_Olfaction/fergus-ssl/fergus_propagation.py", line 132, in predict
    probas = self.predict_proba(X)
  File "Computational_Olfaction/fergus-ssl/fergus_propagation.py", line 164, in predict_proba
    probabilities = np.dot(weight_matrices, self.label_distributions_)
AttributeError: 'FergusPropagation' object has no attribute 'label_distributions_'
_

**Comment by magsol** [comment]
I'm not entirely sure we need this method. `predict_proba` is supposed to give probabilities for each point under each label. It's something we can certainly get to, but for now I'd ignore it.

**Comment by mgadgil09** [comment]
Hello Dr. Quinn,

So as per my understanding, as of now is it the case that we do not need
the predict method
 and I should do the testing only on the fit method? Because at the end of
the fit method we get all the labels.
Please correct me if my understanding is not right.

Thanks,
Madhura Gadgil

**Comment by magsol** [comment]
Yes. For the time being, just the fit method. 

iPhone'd
