### ISSUE TITLE
Change graph laplacian to unnormalized

### ISSUE THREAD

**Issue by magsol** [quinngroup/fergus-ssl#6]
Re-implement `_normalized_graph_laplacian` to instead compute the unnormalized version, or `L = D - A`, where `A` is the affinity / kernel matrix, and `D` is the diagonal matrix.

Feel free to rename the method so it makes sense.

**Comment by mgadgil09** [comment]
Created a new method unnormalized_graph_laplacian to compute unnormalized Laplacian L = D - W.
Also, computing generalized eigenvectors and eigenvalues now.
